# This is a basic workflow to help you get started with Actions

name: Node.js CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        node-version: [12.x]
        # node-version: [10.x, 12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run make
      #- run: npm run build --if-present
      #- run: npm test

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: |
            out/**/*.zip

        env:
          CI: true
